// <auto-generated />
using DotNet2020.Domain._3.Models.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DotNet2020.Data.Migrations.Attestation
{
    [DbContext(typeof(AttestationContext))]
    [Migration("20200317162345_AttestationAdd")]
    partial class AttestationAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DotNet2020.Domain._3.Models.AttestationModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Answers")
                        .HasColumnType("text");

                    b.Property<string>("Feedback")
                        .HasColumnType("text");

                    b.Property<string>("NextMoves")
                        .HasColumnType("text");

                    b.Property<string>("Problems")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Attestations");
                });
#pragma warning restore 612, 618
        }
    }
}
